@props(['title' => null, 'breadcrumbs' => null, 'content' => null])
@extends('adminlte::page')

{{-- Extend and customize the browser title --}}
@section('title')
    {{ config('adminlte.title') }}
    @isset($title)
        | {{ $title }}
    @endisset
@stop

{{-- Add common CSS customizations --}}
@push('css')
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    <style type="text/css">
        html, body {
            font-size: 14px;
        }
    </style>
@endpush

{{-- Add the page content header --}}
@section('content_header')
    <div class="row">
        <div class="col">
            <ol class="breadcrumb">
                {{ $breadcrumbs }}
            </ol>
        </div>
    </div>
@stop

{{-- Add the page content --}}
@section('content')
    {{ $slot }}
@stop

{{-- Create a common footer --}}
@section('footer')
    <b>Copyright</b> © 2021-{{date('Y')}} {{config('app.name')}}
    <div class="float-right d-none d-sm-inline-block">  
        Generated by <a href="https://github.com/adwiv/laravel-crud-generator">Laravel CRUD Generator</a>
    </div>
@stop

{{-- Add common JavaScript customizations --}}
@push('js')
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script>
        $(document).ready(function() {
            // Show toastr messages
            @if(session()->has('success'))
                toastr.success("{{ session('success') }}");
            @endif
            @if(session()->has('warning'))
                toastr.warn("{{ session('warning') }}");
            @endif
            @if(session()->has('info'))
                toastr.info("{{ session('info') }}");
            @endif
            @if(session()->has('error'))
                toastr.error("{{ session('error') }}");
            @endif
        });
    </script>
@endpush